// dictionaries with terminology in English and Japanese.
// Most entries are no longer used after we switched to static translation.

var en_us = {
    'title': 'Tokyo COVID-19 Tracker',
    'lastUpdatedLabel': 'Last Updated:',
    'summary': 'Summary',
    'activeLabel': 'Active',
    'confirmedLabel': 'Confirmed',
    'recoveredLabel': 'Recovered',
    'deathsLabel': 'Deaths',
    'testedLabel': 'Tested',
    'testsLabel': 'Tests',
    'latestTrends': 'Latest Trends',
    'outbreakMapLabel': 'Outbreak Map',
    'selectLabel': 'Select a district',
    'searchWard': 'Search',
    'ageGenderLabel': 'By Age and Gender',
    'confirmedByWard': 'Confirmed Cases by Ward',
    'newsLabel': 'News',
    'aboutLabel': 'This website was created by three college students to better visualize and understand the trends of the COVID-19 outbreak in Tokyo, Japan.',
    'dataSources': 'Data Sources',
    'fukushiUpdates': 'Press releases - Bureau of Social Welfare and Public Health, Tokyo Metro. Govt.',
    'openData': 'Tokyo Metro. Gov. Open Data',
    'male': 'Male',
    'female': 'Female',
    'wardChartLang': 'chart_en',
    'agePostfix': 's',
    'dailyNums': 'Daily Numbers',
    'mapLabels': 'label_en',
    'wardLang': 'ward_en',
    'staySafe': 'Stay safe and informed with real-time analytics from <b>covid19tokyo.live</b>.',
    'dailyCases': 'New cases per day',
    'dailyDeaths': 'New deaths per day',
    'dailyTests': 'New tests per day',
};

var ja = {
    'title': '東京都<span style="display: inline-block;">新型コロナウイルス</span><span style="display: inline-block;">感染状況</span>',
    'lastUpdatedLabel': '最終更新',
    'summary': '現在の状況',
    'activeLabel': '現在患者数',
    'confirmedLabel': '感染者数',
    'recoveredLabel': '退院者数',
    'deathsLabel': '死亡者数',
    'testedLabel': '検査実施人数',
    'testsLabel': '検査実施件数',
    'latestTrends': '最新感染動向',
    'outbreakMapLabel': '感染者数マップ',
    'selectLabel': '区市町村を選択して下さい',
    'searchWard': '区市町村を探す',
    'ageGenderLabel': '年齢・男女別',
    'confirmedByWard': '各区市町村の感染者数',
    'newsLabel': '最新のニュース',
    'aboutLabel': 'このサイトは東京都内の新型コロナウイルス(COVID-19)の最新感染状況が一目で分かるように開発されたダッシュボードです。',
    'dataSources': 'データ出典',
    'fukushiUpdates': '東京都福祉保健局報道発表',
    'openData': '東京都福祉保健局オープンデータ',
    'male': '男性',
    'female': '女性',
    'wardChartLang': 'chart_ja',
    'agePostfix': '代',
    'dailyNums': '日別',
    'mapLabels': 'label_ja',
    'wardLang': 'ward_ja',
    'staySafe': '<b>covid19tokyo.live</b>を使って都内の最新情報を入手。',
    'dailyCases': '新規感染者数',
    'dailyDeaths': '新規死亡者数',
    'dailyTests': '新規検査件数'
};